let D=[],META={},near='all';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
if(!localStorage.getItem('tpb-v7-favs')){const old=localStorage.getItem('tpb-v6-favs')||localStorage.getItem('tpb-v5-favs');if(old)localStorage.setItem('tpb-v7-favs',old)}
const favs=()=>new Set(JSON.parse(localStorage.getItem('tpb-v7-favs')||'[]'));
const NEAR={all:null,jose:['José Américo','Geisel','Entorno UNIPÊ / UFPB','Bancários / UFPB','Bancários','Jardim Cidade Universitária','Cristo Redentor / acesso ao corredor'],geisel:['Geisel','José Américo','Bancários','Bancários / UFPB','Entorno UNIPÊ / UFPB'],bancarios:['Bancários','Bancários / UFPB','Entorno UNIPÊ / UFPB','Jardim Cidade Universitária','José Américo'],mangabeira:['Mangabeira','Jardim Cidade Universitária','Portal do Sol','Paratibe / Litoral Sul'],quadramares:['Portal do Sol','Mangabeira','Seixas'],portal:['Portal do Sol','Seixas','Mangabeira'],penha:['Seixas','Portal do Sol','Barra de Gramame'],seixas:['Seixas','Portal do Sol','Barra de Gramame'],barra:['Barra de Gramame','Rota do Sol / Litoral Sul','Paratibe / Litoral Sul','Zona Sul / acesso PB‑008'],pb008:['Rota do Sol / Litoral Sul','Paratibe / Litoral Sul','Zona Sul / acesso PB‑008','Barra de Gramame','Jacumã','Praia do Amor / Jacumã','Carapibus'],conde:['Jacumã','Praia do Amor / Jacumã','Carapibus'],'casa-lina':['Jacumã','Praia do Amor / Jacumã','Carapibus']};
const LABEL={all:'Base completa',jose:'Perto de José Américo',geisel:'Perto do Geisel',bancarios:'Perto de Bancários / UFPB',mangabeira:'Perto de Mangabeira',quadramares:'Perto de Quadramares',portal:'Perto do Portal do Sol',penha:'Perto da Penha',seixas:'Perto do Seixas',barra:'Perto da Barra de Gramame',pb008:'Eixo PB-008 / Litoral Sul',conde:'Conde / Jacumã','casa-lina':'Perto da Casa Lina'};
function daysSince(iso){if(!iso)return 9999;return Math.floor((Date.now()-new Date(iso+'T12:00:00').getTime())/86400000)}
function maintStatus(x){if(['Inativo','Indisponível'].includes(x.status))return 'Desatualizado';const d=daysSince(x.ultimaVerificacaoISO);if(d>60)return 'Desatualizado';if(d>30)return 'Revisar';return 'Ativo'}
function statusClass(s){return s==='Ativo'?'ok':s==='Revisar'?'review':'stale'}
function toggleFav(id){const f=favs();f.has(id)?f.delete(id):f.add(id);localStorage.setItem('tpb-v7-favs',JSON.stringify([...f]));render()}
function setNear(key,scroll=true){near=key;$$('.near-chip').forEach(b=>b.classList.toggle('active',b.dataset.near===key));$$('.map-node').forEach(b=>b.classList.toggle('active',b.dataset.near===key));$('#contextLabel').textContent=LABEL[key]||'Base completa';render();if(scroll)document.querySelector('.results-head').scrollIntoView({behavior:'smooth',block:'start'})}
function resetAll(){near='all';['q','reg','type','source','maint'].forEach(id=>$('#'+id).value='');['cap','beds','baths'].forEach(id=>$('#'+id).value='0');$('#sort').value='recommended';['pool','parking','air','pet','fav'].forEach(id=>$('#'+id).checked=false);$$('.near-chip').forEach(b=>b.classList.toggle('active',b.dataset.near==='all'));$$('.map-node').forEach(b=>b.classList.remove('active'));$('#contextLabel').textContent='Base completa';render()}
function iconFor(type){return type==='Casa'?'⌂':type==='Estúdio'?'◫':'▦'}
function coverClass(type){return type==='Casa'?'house':type==='Estúdio'?'studio':'apartment'}
function activeFilterPills(){const pills=[];if(near!=='all')pills.push(LABEL[near]);const vals=[['reg','Região'],['type','Tipo'],['source','Origem'],['maint','Status']];vals.forEach(([id,label])=>{if($('#'+id).value)pills.push(label+': '+$('#'+id).selectedOptions[0].text)});[['cap','Hóspedes'],['beds','Quartos'],['baths','Banheiros']].forEach(([id,label])=>{if(+$('#'+id).value)pills.push(label+': '+$('#'+id).value+'+')});[['pool','Piscina'],['parking','Estacionamento'],['air','Ar-condicionado'],['pet','Pet friendly'],['fav','Favoritos']].forEach(([id,label])=>{if($('#'+id).checked)pills.push(label)});if($('#q').value.trim())pills.push('Busca: '+$('#q').value.trim());$('#activeFilters').innerHTML=pills.map(x=>`<span class="filter-pill">${x}</span>`).join('')}
function sortList(list){const mode=$('#sort').value;return list.sort((a,b)=>{if(near==='casa-lina'&&a.id==='casa-lina')return -1;if(near==='casa-lina'&&b.id==='casa-lina')return 1;if(mode==='rating')return (b.nota||0)-(a.nota||0);if(mode==='capacity')return (b.hospedes||0)-(a.hospedes||0);if(mode==='name')return a.nome.localeCompare(b.nome,'pt-BR');if((a.selo==='Perfil oficial')!==(b.selo==='Perfil oficial'))return a.selo==='Perfil oficial'?-1:1;return (b.nota||0)-(a.nota||0)})}
function render(){const f=favs(),q=$('#q').value.trim().toLowerCase(),region=$('#reg').value,type=$('#type').value,cap=+$('#cap').value,beds=+$('#beds').value,baths=+$('#baths').value,source=$('#source').value,maint=$('#maint').value,allowed=NEAR[near];let list=D.filter(x=>{const hay=(x.nome+' '+x.regiao+' '+x.cidade+' '+x.tipo+' '+x.fonte).toLowerCase(),ms=maintStatus(x);return(!allowed||allowed.includes(x.regiao))&&(!q||hay.includes(q))&&(!region||x.regiao===region)&&(!type||x.tipo===type)&&(!cap||x.hospedes===null||x.hospedes>=cap)&&(!beds||x.quartos===null||x.quartos>=beds)&&(!baths||x.banheiros===null||x.banheiros>=baths)&&(!source||(source==='official'?x.selo==='Perfil oficial':x.selo!=='Perfil oficial'))&&(!maint||ms===maint)&&(!$('#pool').checked||x.piscina===true)&&(!$('#parking').checked||x.estacionamento===true)&&(!$('#air').checked||x.ar===true)&&(!$('#pet').checked||x.pet===true)&&(!$('#fav').checked||f.has(x.id))});sortList(list);activeFilterPills();$('#count').textContent=list.length+' '+(list.length===1?'opção':'opções');$('#cards').innerHTML=list.length?list.map(x=>{const ms=maintStatus(x);return`<article class="card"><div class="card-cover ${coverClass(x.tipo)}"><div class="cover-top"><span class="type-badge">${x.tipo}</span><span class="source-badge">${x.selo}</span></div><span class="cover-icon">${iconFor(x.tipo)}</span></div><div class="card-body"><div class="location">📍 ${x.regiao} · ${x.cidade}</div><h3>${x.nome}</h3>${x.hospedes?`<div class="stats"><span>👥 ${x.hospedes>=17?'16+':x.hospedes}</span><span>🛏 ${x.quartos} quarto${x.quartos==1?'':'s'}</span><span>🚿 ${x.banheiros} banheiro${x.banheiros==1?'':'s'}</span></div>`:''}<div class="chips">${x.piscina?'<span class="chip">🏊 Piscina</span>':''}${x.estacionamento?'<span class="chip">🚗 Estacionamento</span>':''}${x.ar?'<span class="chip">❄️ Ar</span>':''}${x.pet?'<span class="chip">🐾 Pet</span>':''}</div><p class="description">${x.detalhe}</p>${x.nota?`<div class="rating"><b>★ ${String(x.nota).replace('.',',')}</b>${x.reviews!==null?` <span>(${x.reviews} avaliações)</span>`:''}</div>`:''}<div class="verify">${x.fonte} · <span class="${statusClass(ms)}">${ms}</span> · verificado em ${x.verificado}</div><div class="actions"><button class="details-btn" type="button" onclick="openDetails('${x.id}')">Ver detalhes</button><a class="open" href="${x.url}" target="_blank" rel="noopener">${x.selo==='Perfil oficial'?'Perfil oficial':'Anúncio'} ↗</a><button class="heart" type="button" aria-label="Favoritar ${x.nome}" onclick="toggleFav('${x.id}')">${f.has(x.id)?'♥':'♡'}</button></div></div></article>`}).join(''):`<div class="empty"><b>Nenhum imóvel encontrado com esta combinação.</b><p>Retire um filtro ou tente uma região vizinha do corredor.</p></div>`}
function updateMaintenance(){const counts={Ativo:0,Revisar:0,Desatualizado:0};D.forEach(x=>counts[maintStatus(x)]++);$('#activeCount').textContent=counts.Ativo;$('#reviewCount').textContent=counts.Revisar;$('#staleCount').textContent=counts.Desatualizado;$('#heroTotal').textContent=D.length;const r=META.politicaRevisao||{revisarAposDias:30,desatualizadoAposDias:60};$('#maintenanceText').textContent=`Revisão automática: ${r.revisarAposDias} dias para revisar; ${r.desatualizadoAposDias} dias para desatualizado.`}
function openDetails(id){const x=D.find(i=>i.id===id);if(!x)return;const m=$('#detailModal'),b=$('#detailBody'),f=favs(),ms=maintStatus(x),amen=[];if(x.piscina)amen.push('🏊 Piscina');if(x.estacionamento)amen.push('🚗 Estacionamento');if(x.ar)amen.push('❄️ Ar-condicionado');if(x.pet)amen.push('🐾 Pet friendly');const cap=x.hospedes?`${x.hospedes>=17?'16+':x.hospedes} hóspedes`:'Consultar',rooms=x.quartos??'Consultar',baths=x.banheiros??'Consultar',rating=x.nota?`★ ${String(x.nota).replace('.',',')}${x.reviews!==null&&x.reviews!==undefined?` · ${x.reviews} avaliações`:''}`:'Sem avaliação cadastrada';b.innerHTML=`<div class="detail-kicker">📍 ${x.regiao} · ${x.cidade}</div><h2 id="detailTitle" class="detail-title">${x.nome}</h2><div class="detail-badges"><span class="chip">${x.tipo}</span><span class="chip">${x.selo}</span><span class="chip">Status: ${ms}</span>${x.destaque?'<span class="chip">★ Destaque</span>':''}</div><p>${x.detalhe||'Consulte os detalhes na fonte original.'}</p><div class="detail-grid"><div class="detail-box"><b>Capacidade</b>${cap}</div><div class="detail-box"><b>Quartos</b>${rooms}</div><div class="detail-box"><b>Banheiros</b>${baths}</div><div class="detail-box"><b>Avaliação</b>${rating}</div><div class="detail-box"><b>Fonte</b>${x.fonte}</div><div class="detail-box"><b>Última conferência</b>${x.verificado}</div></div>${amen.length?`<div class="detail-badges">${amen.map(a=>`<span class="chip">${a}</span>`).join('')}</div>`:''}<div class="detail-actions"><a class="detail-primary" href="${x.url}" target="_blank" rel="noopener">${x.selo==='Perfil oficial'?'Abrir perfil oficial':'Ver anúncio original'} ↗</a><button class="detail-secondary" type="button" onclick="toggleFav('${x.id}');openDetails('${x.id}')">${f.has(x.id)?'♥ Remover dos favoritos':'♡ Adicionar aos favoritos'}</button></div><div class="detail-note">O Temporada PB é um guia independente. Valores, disponibilidade, regras e localização podem mudar. Confirme tudo na fonte original antes de reservar.</div>`;m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeDetails(){const m=$('#detailModal');m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.style.overflow=''}
function updateNetwork(){const online=navigator.onLine;$('#networkBadge').textContent=online?'● Online':'● Offline';$('#networkBadge').classList.toggle('offline',!online);$('#networkBadge').classList.toggle('online',online)}
Promise.all([fetch('data/imoveis.json').then(r=>r.json()),fetch('data/meta.json').then(r=>r.json())]).then(([d,m])=>{D=d;META=m;$('#reg').innerHTML += [...new Set(D.map(x=>x.regiao))].sort((a,b)=>a.localeCompare(b,'pt-BR')).map(x=>`<option value="${x}">${x}</option>`).join('');updateMaintenance();render()}).catch(()=>{$('#cards').innerHTML='<div class="empty"><b>Não foi possível carregar a base.</b><p>Se estiver offline pela primeira vez, conecte-se uma vez para armazenar o aplicativo.</p></div>'});
$$('.near-chip,.map-node').forEach(b=>b.addEventListener('click',()=>setNear(b.dataset.near)));['q','reg','type','cap','beds','baths','source','maint','sort','pool','parking','air','pet','fav'].forEach(id=>$('#'+id).addEventListener('input',render));$('#resetFilters').addEventListener('click',resetAll);$('#clearMap').addEventListener('click',()=>setNear('all'));$('#toggleFilters').addEventListener('click',()=>{const b=$('#filterBody'),collapsed=b.classList.toggle('collapsed');$('#toggleFilters').textContent=collapsed?'Mostrar filtros':'Ocultar filtros'});$('#mobileFav').addEventListener('click',()=>{$('#fav').checked=true;render();document.querySelector('.results-head').scrollIntoView({behavior:'smooth'});});document.addEventListener('click',e=>{if(e.target.closest('[data-close-detail]'))closeDetails()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetails()});window.addEventListener('online',updateNetwork);window.addEventListener('offline',updateNetwork);updateNetwork();
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
